/*
 * Generated by scripts/build-demo-icon-font.mjs - do not edit.
 *
 * Which icon of the demo sits on which code point. Component.ts hands it to
 * IconPool.registerFont, and that is the point of this file: without it
 * IconPool has to fetch ui5-touch-controls-demo-icons.json first, and an
 * icon rendered before that answer arrives is rendered empty - and stays
 * empty, because nothing renders it again once the metadata turns up.
 */

/** the font family of the icons of the demo */
export const ICON_FONT_FAMILY = "ui5-touch-controls-demo-icons";

/** the collection they are addressed by: sap-icon://demo/<name> */
export const ICON_FONT_COLLECTION = "demo";

/**
 * Which icon sits on which code point.
 *
 * A fresh object every time: IconPool takes what it is given and turns the
 * code points into numbers in place.
 */
export function iconFontMetadata(): Record<string, string> {
	return {
		"barcode-input": "e000",
		"button": "e001",
		"check-box": "e002",
		"combo-box": "e003",
		"custom-keyboard": "e004",
		"date-picker": "e005",
		"input": "e006",
		"keyboard-base": "e007",
		"keyboard": "e008",
		"link": "e009",
		"number-pad": "e00a",
		"overflow-toolbar": "e00b",
		"quick-dialog": "e00c",
		"radio-button": "e00d",
		"segmented-button": "e00e",
		"select": "e00f",
		"signature-pad": "e010",
		"step-input": "e011",
		"switch": "e012",
		"text-area": "e013",
		"text": "e014",
		"time-picker": "e015",
		"toolbar": "e016",
	};
}
