/*
 * Generated by scripts/build-icon-font.mjs - do not edit.
 *
 * The metadata of the icon font of this library: which icon sits on which
 * code point. library.ts hands it to IconPool.registerFont, and that is the
 * point of this file. Without it IconPool has to fetch
 * ui5-touch-controls-icons.json first, and an icon that is rendered
 * before that answer arrives is rendered empty - and stays empty, because
 * nothing renders it again once the metadata turns up. Opening a page of
 * keys as the first page of an app is fast enough to lose that race.
 */

/** the font family of the icons of this library */
export const ICON_FONT_FAMILY = "ui5-touch-controls-icons";

/** the collection the icons are addressed by: sap-icon://touch/<name> */
export const ICON_FONT_COLLECTION = "touch";

/**
 * Which icon sits on which code point.
 *
 * A fresh object every time: IconPool takes what it is given and turns the
 * code points into numbers in place.
 */
export function iconFontMetadata(): Record<string, string> {
	return {
		backspace: "e000",
		enter: "e001",
	};
}
